### ISSUE TITLE
Wiring documentation is not correct for Serial lines from Pixhawk to MKRZero

### ISSUE THREAD

**Issue by KenLagoni** [KenLagoni/MavlinkGPRS#2]
The documentation incorrectly state:
Pixhawk TX-> MKZzero pin 8 (RX)
Pixhawk RX<- MKZzero pin 9 (TX)

But instead it should be:
Pixhawk TX-> MKZzero pin 13 (RX)
Pixhawk RX<- MKZzero pin 14 (TX)

**Comment by mohanbabi** [comment]
@KenLagoni  sir, it is better to change the diagram, sir. That is my opinion.


Thank you Sir

**Comment by KenLagoni** [comment]
> @KenLagoni sir, it is better to change the diagram, sir. That is my opinion.
> 
> Thank you Sir

Yes that is what is says, the documentation must be updated (the diagram). :-)

**Comment by KenLagoni** [comment]
Solved, thank you @mohanbabi  :-)

**Comment by mohanbabi** [comment]
thank you sir
